import React,{useEffect,useState}from"react";import{createRoot}from"react-dom/client";import"./style.css";
const API=import.meta.env.VITE_API_URL??"http://localhost:8080";
type Me={id:string;role:string;full_name:string;email:string};type Session={id:string;status:string;started_at:string;code?:string;title?:string;term?:string;checked_in?:boolean};
async function api(path:string,opts:RequestInit={}){const token=sessionStorage.getItem("accessToken");const h=new Headers(opts.headers);h.set("Content-Type","application/json");if(token)h.set("Authorization",`Bearer ${token}`);const r=await fetch(API+path,{...opts,headers:h,credentials:"include"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??"request_failed");return d}
function App(){const[me,setMe]=useState<Me|null>(null);const[sessions,setSessions]=useState<Session[]>([]);const[email,setEmail]=useState("");const[password,setPassword]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);
async function load(u:Me){setMe(u);try{const d=u.role==="student"?await api("/student/sessions"):u.role==="professor"?await api("/professor/sessions"):await api("/me");setSessions(Array.isArray(d)?d:[])}catch{}}
async function login(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const d=await api("/auth/login",{method:"POST",body:JSON.stringify({email,password})});sessionStorage.setItem("accessToken",d.accessToken);await load(await api("/me"));}catch(e){setError(e instanceof Error?e.message:"Login failed")}finally{setBusy(false)}}
if(!me)return <main className="shell"><section className="card login"><div className="brand">SHAHID</div><p className="muted">Attendance Integrity Platform</p><form onSubmit={login}><label>Email<input value={email}onChange={e=>setEmail(e.target.value)}type="email"required/></label><label>Password<input value={password}onChange={e=>setPassword(e.target.value)}type="password"required/></label>{error&&<div className="error">{error}</div>}<button disabled={busy}>{busy?"Signing in…":"Sign in"}</button></form><small>Evidence-first attendance integrity. No automatic accusation.</small></section></main>;
return <main className="shell"><header><div><div className="brand">SHAHID</div><div className="muted">{me.role} workspace · {me.full_name}</div></div><button className="ghost"onClick={()=>{sessionStorage.removeItem("accessToken");setMe(null)}}>Sign out</button></header><section className="grid"><article className="card"><span className="eyebrow">IDENTITY</span><h2>{me.full_name}</h2><p>{me.email}</p><strong>{me.role}</strong></article><article className="card"><span className="eyebrow">EVIDENCE MODEL</span><h2>Multi-source</h2><p>Cryptographic device proof, signed witness observations, BLE proximity and liveness are evaluated server-side.</p></article><article className="card wide"><span className="eyebrow">{me.role==="student"?"ACTIVE SESSIONS":"YOUR SESSIONS"}</span><h2>{sessions.length} session{sessions.length===1?"":"s"}</h2>{sessions.length===0?<p className="muted">No sessions available.</p>:sessions.map(s=><div className="status"key={s.id}><span><b>{s.code??"Session"}</b> {s.title??""}<br/><small>{new Date(s.started_at).toLocaleString()}</small></span><b>{s.checked_in?"Checked in":s.status}</b></div>)}</article></section></main>}
createRoot(document.getElementById("root")!).render(<App/>);