import React,{useEffect,useMemo,useState}from"react";
import{createRoot}from"react-dom/client";
import"./style.css";

const API=import.meta.env.VITE_API_URL??"http://localhost:8080";
type Me={id:string;role:string;full_name:string;email:string};
type Session={id:string;status:string;started_at:string;ended_at?:string;code?:string;title?:string;term?:string};
type Section={id:string;course_id:string;code:string;title:string;term:string;enrolled_count:number};
type Student={deviceId:string;witnessCount:number;outcome:string;riskScore:number|null;riskState?:string;confidence?:number|null;reasons?:string[]};
async function api(path:string,opts:RequestInit={}){const token=sessionStorage.getItem("accessToken");const h=new Headers(opts.headers);h.set("Content-Type","application/json");if(token)h.set("Authorization",`Bearer ${token}`);const r=await fetch(API+path,{...opts,headers:h,credentials:"include"});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error??`HTTP ${r.status}`);return d}

function Login({onLogin}:{onLogin:(m:Me)=>void}){const[email,setEmail]=useState("");const[pw,setPw]=useState("");const[error,setError]=useState("");const[busy,setBusy]=useState(false);async function submit(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{const d=await api("/auth/login",{method:"POST",body:JSON.stringify({email,password:pw})});sessionStorage.setItem("accessToken",d.accessToken);const me=await api("/me");onLogin(me)}catch(e){setError(e instanceof Error?e.message:"Login failed")}finally{setBusy(false)}}return <main className="login-page"><form className="login-card" onSubmit={submit}><div className="brand">SHAHID<span>/CONTROL</span></div><p className="muted">Attendance integrity & evidence platform</p><label>Email<input value={email}onChange={e=>setEmail(e.target.value)}type="email"required/></label><label>Password<input value={pw}onChange={e=>setPw(e.target.value)}type="password"required/></label>{error&&<div className="error">{error}</div>}<button disabled={busy}>{busy?"AUTHENTICATING…":"SIGN IN"}</button><small>Server: {API}</small></form></main>}

function Shell({me,onLogout,children}:{me:Me;onLogout:()=>void;children:React.ReactNode}){return <div className="app"><aside><div className="brand">SHAHID<span>/CONTROL</span></div><div className="role">{me.role.replaceAll("_"," ")}</div><nav><a href="#home">Overview</a>{me.role==="professor"&&<><a href="#sessions">Sessions</a><a href="#evidence">Evidence Graph</a></>}{me.role!=="student"&&<><a href="#security">Security</a><a href="#users">Users</a></>}</nav><div className="identity"><b>{me.full_name}</b><span>{me.email}</span><button className="ghost"onClick={onLogout}>Sign out</button></div></aside><main className="content">{children}</main></div>}

function Professor({me}:{me:Me}){const[sections,setSections]=useState<Section[]>([]);const[sessions,setSessions]=useState<Session[]>([]);const[selected,setSelected]=useState("");const[data,setData]=useState<any>(null);const[graph,setGraph]=useState<any>(null);const[error,setError]=useState("");const load=async()=>{try{const[a,b]=await Promise.all([api("/professor/sections"),api("/professor/sessions")]);setSections(a.sections??[]);setSessions(b.sessions??[])}catch(e){setError(String(e))}};useEffect(()=>{load()},[]);useEffect(()=>{if(!selected)return;let dead=false;const run=async()=>{try{const d=await api(`/sessions/${selected}/dashboard`);if(!dead)setData(d);const g=await api(`/sessions/${selected}/evidence-graph`);if(!dead)setGraph(g)}catch(e){if(!dead)setError(String(e))}};run();const id=setInterval(run,3000);return()=>{dead=true;clearInterval(id)}},[selected]);async function create(){const sectionId=sections[0]?.id;if(!sectionId){setError("No owned section available.");return}try{const s=await api("/sessions",{method:"POST",body:JSON.stringify({sectionId})});setSelected(s.id);await load()}catch(e){setError(String(e))}}async function end(){if(!selected)return;try{await api(`/sessions/${selected}/end`,{method:"POST",body:"{}"});await load()}catch(e){setError(String(e))}}return <><header className="top"><div><span className="eyebrow">PROFESSOR CONTROL CENTER</span><h1>Live Attendance</h1></div><div className="actions"><button onClick={create}>+ START SESSION</button>{selected&&<button className="danger"onClick={end}>END SESSION</button>}</div></header>{error&&<div className="error">{error}</div>}<section className="cards"><Metric title="Present" value={data?.presentCount??"—"}/><Metric title="Absent" value={data?.absentCount??"—"}/><Metric title="Flagged" value={data?data.students?.filter((s:Student)=>(s.riskScore??-1)>=.6).length:"—"}/><Metric title="Evidence nodes" value={graph?.nodes?.length??"—"}/></section><section className="panel"><div className="panel-head"><h2>Session selector</h2><select value={selected}onChange={e=>setSelected(e.target.value)}><option value="">Select active/recent session</option>{sessions.map(s=><option key={s.id}value={s.id}>{s.code??"Session"} · {new Date(s.started_at).toLocaleString()} · {s.status}</option>)}</select></div>{data?<Attendance data={data}/>:<Empty text="Start or select a session to monitor live evidence."/>}</section><section id="evidence" className="panel"><div className="panel-head"><h2>Evidence Graph</h2><span className="muted">server-derived · session scoped</span></div><Graph graph={graph}/></section></>}

function Attendance({data}:{data:any}){return <div className="table"><div className="tr th"><span>Participant</span><span>Check-in</span><span>Witnesses</span><span>Risk</span><span>Confidence</span></div>{(data.students??[]).map((s:Student)=><div className="tr"key={s.deviceId}><span>{s.deviceId}</span><span className="badge">{s.outcome}</span><span>{s.witnessCount}</span><span className={(s.riskScore??0)>=.6?"risk":""}>{s.riskState??(s.riskScore==null?"—":s.riskScore.toFixed(2))}</span><span>{s.confidence==null?"—":s.confidence.toFixed(2)}</span></div>)}</div>}
function Graph({graph}:{graph:any}){if(!graph)return <Empty text="No graph data for this session yet."/>;return <div className="graph"><div className="graph-grid">{(graph.edges??[]).map((e:any,i:number)=><div className="edge"key={i}><b>{e.type??e.evidenceType}</b><span>{e.source??e.observerDeviceId??"observer"} → {e.target??e.observedDeviceId??e.studentId??"session"}</span><small>{e.timestamp??e.observedAt??""}</small></div>)}</div></div>}
function Admin(){const[data,setData]=useState<any>(null);const[users,setUsers]=useState<any[]>([]);useEffect(()=>{Promise.all([api("/admin/overview"),api("/admin/users")]).then(([a,b])=>{setData(a);setUsers(b.users??[])}).catch(()=>{})},[]);return <><header className="top"><div><span className="eyebrow">SECURITY CONTROL CENTER</span><h1>Administration</h1></div></header><section className="cards"><Metric title="Users" value={data?.users?.reduce((n:any,x:any)=>n+x.count,0)??"—"}/><Metric title="Devices" value={data?.devices?.reduce((n:any,x:any)=>n+x.count,0)??"—"}/><Metric title="Sessions" value={data?.sessions??"—"}/><Metric title="Risk assessments" value={data?.riskAssessments??"—"}/></section><section id="users"className="panel"><div className="panel-head"><h2>Users</h2><span className="muted">{users.length} records</span></div><div className="table">{users.map(u=><div className="tr"key={u.id}><span>{u.full_name}</span><span>{u.email}</span><span className="badge">{u.role}</span><span>{new Date(u.created_at).toLocaleString()}</span></div>)}</div></section><section id="security"className="panel"><div className="panel-head"><h2>Audit stream</h2></div><div className="table">{(data?.audit??[]).map((a:any)=><div className="tr"key={a.id}><span>{a.action}</span><span>{a.target_table}:{a.target_id}</span><span>{a.reason_code}</span><span>{new Date(a.created_at).toLocaleString()}</span></div>)}</div></section></>}
function Metric({title,value}:{title:string;value:React.ReactNode}){return <article className="metric"><span>{title}</span><strong>{value}</strong></article>}
function Empty({text}:{text:string}){return <div className="empty">{text}</div>}

function App(){const[me,setMe]=useState<Me|null>(null);useEffect(()=>{if(sessionStorage.getItem("accessToken"))api("/me").then(setMe).catch(()=>sessionStorage.removeItem("accessToken"))},[]);if(!me)return <Login onLogin={setMe}/>;const admin=["dept_admin","university_admin","platform_admin"].includes(me.role);return <Shell me={me} onLogout={()=>{sessionStorage.clear();setMe(null)}}>{me.role==="professor"?<Professor me={me}/>:admin?<Admin/>:<><header className="top"><div><span className="eyebrow">STUDENT</span><h1>My Attendance</h1></div></header><div className="panel"><Empty text="Use the SHAHID mobile application for device enrollment, cryptographic check-in and BLE evidence collection."/></div></>}</Shell>}
createRoot(document.getElementById("root")!).render(<App/>);